### ISSUE TITLE
Context Menu to show related elements

### ISSUE THREAD

**Issue by UTNAK** [opencaesar/oml-vision#59]
## Checklist before submitting a feature request

- [X] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [X] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

As a systems engineer, it's nice to have a context menu to show related elements to explore models.

## Describe the desired feature

When I click the nodes in diagram views, I would like to see the related elements of a node like this.

<img width="1379" alt="スクリーンショット 2024-05-02 6 31 25" src="https://github.com/opencaesar/oml-vision/assets/29029659/528d4466-5e28-4e15-a4e3-67b8410d9185">

Here is an example sparql query to get the related elements.

<img width="942" alt="スクリーンショット 2024-05-02 6 31 41" src="https://github.com/opencaesar/oml-vision/assets/29029659/feee04d0-73d1-46a6-bd51-abcd34adbe48">

## Additional context

This is inspired by the new feature of a modal function of the oml-vision.

**Comment by pogi7** [comment]
@UTNAK Do you think it makes sense to also add search capability like the following:
<img width="1273" alt="image" src="https://github.com/opencaesar/oml-vision/assets/108915844/6a00312b-0444-404d-abdc-75d08a6b4a42">

Related elements may be a lot for the modal to render as the model grows and having a search capability will help users look for information they need.

I also feel that pagination is a good feature to have as well.

![image](https://github.com/opencaesar/oml-vision/assets/108915844/2b226801-ade9-4c31-95c9-05c187bf6697)

**Comment by UTNAK** [comment]
> @UTNAK Do you think it makes sense to also add search capability like the following:

Yes, I agree with you, @pogi7!!

**Comment by pogi7** [comment]
@UTNAK I feel that since this query is very generic it can be used in a lot of different OML models.  I feel that this modal should open on a double click.  I can test with you to see if this user experience meets your business needs.  (Also I feel that it would be nice to add a double click feature somewhere in the diagram view :) )

The query can be simplified to this

```sparql
SELECT ?subject
  WHERE {
    BIND(<${iri}> as ?object)
    ?subject ?verb ?object .
  }
```
where the iri is a generic iri related to the selected model element.  We can add a filter to your query as well, but I don't think we need that at the moment.
